#!/bin/bash 
# Runs after rcup 
# Note: if multiple files put in directory:
# "$DOTFILES_DIRS"/hooks/post-up/* 

if [ ! -e "$HOME"/.vim/bundle/Vundle.vim ]; then
	git clone https://github.com/gmarik/Vundle.vim.git "$HOME"/.vim/bundle/Vundle.vim
fi

vim -u ~/.vimrc.bundles +PluginInstall +qall


